# Routes de l'application
routes:

# Exemple d'une route
#  helper_route:
#    method: 'GET|POST'
#    path: '/test'
#    class: FakeNamespace\MySuperBlog\Controller\FakeController#fakeMethod
#    action: test
#    name: test_page

  security_controller_register:
    method: 'GET|POST'
    path: '/register'
    class: App\Admin\SecurityController
    action: register
    name: register_page

  security_controller_login:
    method: 'GET|POST'
    path: '/login'
    class: App\Admin\SecurityController
    action: login
    name: login_page

  security_controller_logout:
    method: 'GET|POST'
    path: '/logout'
    class: App\Admin\SecurityController
    action: logout
    name: logout_page

    #Administration des pages 'Articles'
  admin_post_list:
    method: 'GET'
    path: '/intranet/post/list'
    class: App\Admin\PostControllerAdmin
    action: list
    name: admin_post_list

  admin_post_create:
    method: 'GET, POST'
    path: '/intranet/post/create'
    class: App\Admin\PostControllerAdmin
    action: create
    name: admin_post_create

  admin_post_edit:
    method: 'GET, POST'
    path: '/intranet/post/[i:id]/edit'
    class: App\Admin\PostControllerAdmin
    action: edit
    name: admin_post_edit

  admin_post_delete:
    method: 'GET'
    path: '/intranet/post/[i:id]/delete'
    class: App\Admin\PostControllerAdmin
    action: delete
    name: admin_post_delete

  